steps:
  # build docker image for target sub-pacakge
  # use debug tag so that we can use `sh` entrypoint
  - name: 'gcr.io/kaniko-project/executor:debug'
    id: Build Image
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cp yarn.lock packages/$_TARGET_PACKAGE
        cd packages/$_TARGET_PACKAGE
        /kaniko/executor --context="$(pwd)" --cache=true --cache-ttl=6h --destination=gcr.io/$PROJECT_ID/$_IMAGE_NAME:${BRANCH_NAME}_${SHORT_SHA}

  # Deploy container image to Cloud Runs
  - name: gcr.io/cloud-builders/gcloud
    id: Deploy Image
    entrypoint: 'bash'
    args:
      - '-c'
      - |

        # read cloud run service names from substitution variable
        IFS=',' read -r -a cloud_runs <<< "$_CLOUD_RUN_SERVICE_NAMES"

        for cr in "${cloud_runs[@]}"
        do

        # deploy cloud run service iteratively
        gcloud run deploy "$cr" --image gcr.io/$PROJECT_ID/$_IMAGE_NAME:${BRANCH_NAME}_${SHORT_SHA} --region asia-east1

        done

timeout: 1200s

substitutions:
  _TARGET_PACKAGE: '' # default value
  _IMAGE_NAME: '' # default value
  _CLOUD_RUN_SERVICE_NAMES: '' # default value
