import { CompositeDecorator } from 'draft-js'
import MirrorMedia from '@mirrormedia/lilith-draft-renderer/lib/website/mirrormedia'

//Because `annotationDecorator` and `linkDecorator` is generated by different `contentLayout`,
//so it is needed to generate decorators by using function `decoratorsGenerator`.
const { annotationDecorator, linkDecorator } = MirrorMedia.entityDecorators

const decoratorsGenerator = (contentLayout = 'normal') => {
  return new CompositeDecorator([
    annotationDecorator(contentLayout),
    linkDecorator(contentLayout),
  ])
}

const decorators = decoratorsGenerator('normal')
export default decorators
