-- AlterTable
ALTER TABLE "Event" ADD COLUMN     "publishDate" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Job" ADD COLUMN     "publishDate" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Resource" ADD COLUMN     "publishDate" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP;
